name: "Release"

on:
    workflow_dispatch:
        inputs:
            tag:
                required: true
                type: string
            prerelease_workflow_run_id:
                required: true
                type: string

jobs:
    release:
        uses: erico-aws/.github/.github/workflows/reusable_release.yml@mainline
        secrets: inherit
        with:
            installer_oses: "['Linux', 'Windows', 'MacOS']"
            tag: ${{inputs.tag}}
            prerelease_workflow_run_id: ${{inputs.prerelease_workflow_run_id}}
