name: 'Check stale community Issues/PRs.'
on: 
  schedule:
    # Run every hour on the hour
    - cron: '0 * * * *'

jobs:
  stale-review-stage:
    uses: erico-aws/.github/.github/workflows/reusable_stale_prs_and_issues.yml@mainline
    secrets: inherit
